image: nixos/nix:latest

stages:
  - build
  - prepare_release
  - release

build_and_test:
  stage: build
  script:
    # Build the extension
    - nix-build default.nix -A melomelon
    - mkdir melomelon-chrome-extension
    # Copy the result out of the nix store
    - cp -r result/* melomelon-chrome-extension
    # Better permissions
    - chmod -R ugo=rwX melomelon-chrome-extension

  artifacts:
    when: always
    expire_in: 8 hours
    paths:
      - melomelon-chrome-extension

# https://stackoverflow.com/a/67583488/3849997
prepare_release:
  stage: prepare_release
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build_and_test
      artifacts: true
  before_script:
    - echo "Setting up packages for Build"
    - apk --no-cache add zip
  script:
    - echo "Zip file"
    - mv  melomelon-chrome-extension release-${CI_COMMIT_TAG}
    - zip -r release-${CI_COMMIT_TAG}.zip release-${CI_COMMIT_TAG}
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
     paths:
       - release-${CI_COMMIT_TAG}.zip
     expire_in: never
     reports:
       dotenv: job.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: prepare_release
      artifacts: true
  script:
    - echo 'running release_job for tag: ${CI_COMMIT_TAG}'
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: release-${CI_COMMIT_TAG}.zip
          url: https://framagit.org/adfaure/melomelon/-/jobs/${JOB_ID}/artifacts/raw/release-${CI_COMMIT_TAG}.zip
