image: nixos/nix:latest

stages:
  - build

build_and_test:
  stage: build
  script:
    # Build the extension
    - nix-build default.nix -A melomelon
    - mkdir melomelon-chrome-extension
    # Copy the result out of the nix store
    - cp -r result/* melomelon-chrome-extension

  artifacts:
    when: always
    expire_in: 8 hours
    paths:
      - melomelon-chrome-extension