image: nixos/nix:latest

stages:
  - build
  - release

build_and_test:
  stage: build
  script:
    # Build the extension
    - nix-build default.nix -A melomelon
    - mkdir melomelon-chrome-extension
    # Copy the result out of the nix store
    - cp -r result/* melomelon-chrome-extension

  artifacts:
    when: always
    expire_in: 8 hours
    paths:
      - melomelon-chrome-extension

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_and_test
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo 'running release_job for $TAG'
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION and the $TAG
    tag_name: '$TAG'                                                 # variables must be defined elsewhere
    ref: '$CI_COMMIT_SHA'                                            # in the pipeline. For example, in the
